### ISSUE TITLE
[SUGGESTION] Keep an Eye On Top Command

### ISSUE THREAD

**Issue by Danc2050** [TPU-Mersenne-Prime-Search/TensorPrime#25]
When making sure that JAX is using the TPU, I'd keep an eye on top in the terminal. The attached photo is Tensorflow version and it seems to be using 83%+/100% of the CPU. Like you guys mentioned, there are CPU operations that dominate the CPU, but 83% is a suspiciously high number that would make me want to investigate. It sounds like there is a plan to use one file and stick with JAX, but just a recommendation here on checking ourselves.

![image](https://user-images.githubusercontent.com/32185616/154617956-ed464478-1b31-4cfb-8657-81c1632f1b62.png)

**Comment by WillFarris** [comment]
Our current version of the code sees about 60% CPU usage when using the TPU runtime. This seems roughly in line with the profiling we've been able to do, where roughly 70% of the PRP loop is spent on the carry step, which is performed on the CPU.
